name: .NET CI with MSBuild

on:
  workflow_dispatch:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-2019
    env:
      Solution_Name: Wreck.sln
      Configuration: Release
      
    steps:
      - name: Setup .NET Framework 3.5
        run: Enable-WindowsOptionalFeature -Online -FeatureName "NetFx3" -All
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build solution
        run: C:\Windows\Microsoft.NET\Framework\v3.5\MSBuild.exe Wreck.sln -t:Rebuild -p:Configuration=Release -p:Platform=x86 -p:TargetFrameworkVersion=v2.0
        env:
          Configuration: ${{ matrix.configuration }}
          
      - name: Prepare upload artifact
        run: |
          mkdir -p /tmp/upload
          cp LICENSE.txt /tmp/upload
          cp -r Dependencies/* /tmp/upload
          cp -r Wreck/bin/Release/* /tmp/upload
          cp -r WreckCli/bin/Release/* /tmp/upload
          cp -r WreckGui/bin/Release/* /tmp/upload          
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wreck
          path: /tmp/upload
          if-no-files-found: error
          retention-days: 1
          
            
          
