name: MSBuild

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-2019
    env:
      Solution_Name: Wreck.sln
      Configuration: Release
      
    steps:
      - name: Cache .Net Framework 3.5
        id: cache-net-framework-35
        uses: actions/cache@v3
        env:
          cache-name: cache-net-framework-35
        with:
          path: |
            C:/Windows/Microsoft.NET/Framework/v2.0.50727
            C:/Windows/Microsoft.NET/Framework/v3.0
            C:/Windows/Microsoft.NET/Framework/v3.5
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - if: ${{ steps.cache-net-framework-35.outputs.cache-hit != 'true' }}    
        name: Setup .NET Framework 3.5
        continue-on-error: true
        run: Enable-WindowsOptionalFeature -Online -FeatureName "NetFx3" -All
      
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build solution
        run: C:\Windows\Microsoft.NET\Framework\v3.5\MSBuild.exe Wreck.sln -t:Rebuild -p:Configuration=Release -p:Platform=x86 -p:TargetFrameworkVersion=v2.0
        env:
          Configuration: ${{ matrix.configuration }}
          
      - name: Prepare upload artifact
        run: |
          mkdir -p /tmp/upload
          cp LICENSE.txt /tmp/upload
          cp -r Dependencies/* /tmp/upload
          cp -r Wreck/bin/Release/* /tmp/upload
          cp -r WreckCli/bin/Release/* /tmp/upload
          cp -r WreckGui/bin/Release/* /tmp/upload          
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: wreck
          path: /tmp/upload
          if-no-files-found: error
          retention-days: 1
          
            
          
